name:            s1_AS1
crl_interval:    5m
regen_margin:    2m
valid_for:       2d
kids:
  - name: s2_AS2
    asn: 2
    ipv4: 10.1.0.0/16
    roa_request:
      - asn: 2
        ipv4: 10.1.0.33/32
      - asn: 2
        ipv4: 10.1.0.20/30
      - asn: 2
        ipv4: 10.1.0.34/32
      - asn: 2
        ipv4: 10.1.0.12/30
      - asn: 2
        ipv4: 10.1.0.35/32
      - asn: 2
        ipv4: 10.1.0.24/30
      - asn: 2
        ipv4: 10.1.0.16/30
      - asn: 2
        ipv4: 10.2.0.20/30
      - asn: 2
        ipv4: 10.4.0.8/30
      - asn: 2
        ipv4: 10.1.0.32/32
      - asn: 2
        ipv4: 10.0.0.0/30
    kids:
      - name: s5_AS5
        asn: 5
        ipv4: 10.4.0.0/16
        roa_request:
          - asn: 5
            ipv4: 10.4.0.34/32
          - asn: 5
            ipv4: 10.4.0.16/30
          - asn: 5
            ipv4: 10.4.0.33/32
          - asn: 5
            ipv4: 10.4.0.12/30
          - asn: 5
            ipv4: 10.4.0.32/32
          - asn: 5
            ipv4: 10.4.0.8/30
      - name: s3_AS3
        asn: 3
        ipv4: 10.2.0.0/16
        roa_request:
          - asn: 3
            ipv4: 10.2.0.34/32
          - asn: 3
            ipv4: 10.2.0.24/30
          - asn: 3
            ipv4: 10.2.0.12/30
          - asn: 3
            ipv4: 10.2.0.20/30
          - asn: 3
            ipv4: 10.2.0.8/30
          - asn: 3
            ipv4: 10.2.0.33/32
          - asn: 3
            ipv4: 10.2.0.32/32
          - asn: 3
            ipv4: 10.2.0.35/32
      - name: s4_AS4
        asn: 4
        ipv4: 10.3.0.0/16
        roa_request:
          - asn: 4
            ipv4: 10.3.0.33/32
          - asn: 4
            ipv4: 10.3.0.4/30
          - asn: 4
            ipv4: 10.3.0.16/30
          - asn: 4
            ipv4: 10.1.0.24/30
          - asn: 4
            ipv4: 10.3.0.20/30
          - asn: 4
            ipv4: 10.3.0.35/32
          - asn: 4
            ipv4: 10.3.0.34/32
          - asn: 4
            ipv4: 10.3.0.32/32